### ISSUE TITLE
Collaborate on the official HN PWA example?

### ISSUE THREAD

**Issue by matanlurey** [pd4d10/dart-hn#1]
First off, thanks so much for this example and your enthusiasm around AngularDart. You rock!

We found your example live on the web, and have our own implementation over here (https://github.com/dart-lang/angular/tree/master/examples/hacker_news_pwa) on the AngularDart repository. They are very similar - ours uses the latest AngularDart v5 and new build system, but otherwise, similar.

Would love to collaborate if you are interested.

You can view our live demo here: dart-hn.firebaseapp.com

**Comment by pd4d10** [comment]
@matanlurey The official HN PWA is awesome. 👍 I'm in
